import { useRef, useState, useEffect, useCallback, memo } from "react";
import { motion, AnimatePresence } from "framer-motion";

/* ─────────────────────────────────────────────
   TYPES
───────────────────────────────────────────── */
interface Project {
  id: number;
  category: string;
  title: string;
  description: string;
  features: string[];
  stack: string[];
  color: string;
  link: string;
  github: string;
  year: string;
  role: string;
  status: string;
  featured: boolean;
  images: {
    topLeft: string;
    bottomLeft: string;
    right: string;
    thumb: string;
  };
}

/* ─────────────────────────────────────────────
   DATA
───────────────────────────────────────────── */
const PROJECTS: Project[] = [
  {
    id: 1,
    category: "PRODUCTIVITY · SAAS",
    title: "Rune",
    description:
      "All-in-one productivity toolkit featuring 145+ powerful tools for learning, creating, and working smarter — text editors, PDF management, image editing, video processing, developer utilities, and AI-powered assistants.",
    features: [
      "145+ free tools including text editors, PDF converters, and image processors",
      "AI-powered tools for writing, summarising, and content creation",
      "Developer utilities with JSON formatter, regex tester, and code tools",
    ],
    stack: ["React", "TypeScript", "Next.js", "Tailwind CSS", "RuneAI"],
    color: "#c0392b",
    link: "#",
    github: "#",
    year: "2024",
    role: "Full-Stack Developer",
    status: "Live",
    featured: true,
    images: {
      topLeft: "https://placehold.co/480x320/1a1a1a/ffffff?text=Rune+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Rune+Mobile+2",
      right: "https://placehold.co/800x600/111111/ffffff?text=Rune+Desktop",
      thumb: "https://placehold.co/600x400/140a0a/ffffff?text=Rune",
    },
  },
  {
    id: 2,
    category: "EDUCATION · AI",
    title: "RuneLearn",
    description:
      "AI-powered study companion that dynamically generates quizzes, intelligent flashcards, personalised roadmaps, and instantly resolves doubts with a deep-context advanced solver designed to turbocharge long-term memory.",
    features: [
      "Interactive Quizzes and Flashcards dynamically generated by AI",
      "Personalised Learning Roadmaps tailored to your study goals",
      "Advanced Doubt Solver providing in-depth explanations instantly",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "RuneAI",
      "Vercel",
    ],
    color: "#b45309",
    link: "#",
    github: "#",
    year: "2024",
    role: "Frontend Developer",
    status: "Live",
    featured: true,
    images: {
      topLeft: "https://placehold.co/480x320/1a1a1a/ffffff?text=Learn+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Learn+Mobile+2",
      right: "https://placehold.co/800x600/111111/ffffff?text=Learn+Desktop",
      thumb: "https://placehold.co/600x400/100c00/ffffff?text=RuneLearn",
    },
  },
  {
    id: 3,
    category: "PORTFOLIO · TEMPLATE",
    title: "ParthSharma.me",
    description:
      "Premium, high-performance portfolio crafted for the modern web. Featuring fluid GSAP animations, physics-based interactions, and a polished aesthetic built with Next.js, Prisma, and Zustand.",
    features: [
      "Premium high-performance design with fluid GSAP animations",
      "Physics-based interactions and advanced state management with Zustand",
      "Robust full-stack architecture with Prisma and PostgreSQL",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Node.js",
      "GSAP",
      "Prisma",
      "Zustand",
      "Motion",
    ],
    color: "#7c3aed",
    link: "#",
    github: "#",
    year: "2025",
    role: "Designer & Developer",
    status: "Live",
    featured: true,
    images: {
      topLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Portfolio+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Portfolio+Mobile+2",
      right:
        "https://placehold.co/800x600/111111/ffffff?text=Portfolio+Desktop",
      thumb: "https://placehold.co/600x400/0d0814/ffffff?text=Portfolio",
    },
  },
  {
    id: 4,
    category: "HEALTH · MOBILE",
    title: "NeuroSpeak",
    description:
      "AI-powered assistive communication app for non-verbal users and caregivers, featuring role-based dashboards, speech-to-text, text-to-speech, emergency alerts with live location, and real-time emotion detection.",
    features: [
      "Role-based dashboards for users and caregivers with real-time sync",
      "Emergency alert system with live GPS location sharing",
      "Emotion detection powered by on-device ML models",
    ],
    stack: [
      "React",
      "TypeScript",
      "Supabase",
      "TensorFlow.js",
      "Tailwind CSS",
      "Vercel",
    ],
    color: "#0891b2",
    link: "#",
    github: "#",
    year: "2024",
    role: "Full-Stack Developer",
    status: "In Review",
    featured: true,
    images: {
      topLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=NeuroSpeak+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=NeuroSpeak+Mobile+2",
      right:
        "https://placehold.co/800x600/111111/ffffff?text=NeuroSpeak+Desktop",
      thumb: "https://placehold.co/600x400/020f14/ffffff?text=NeuroSpeak",
    },
  },
  {
    id: 5,
    category: "FINANCE · DASHBOARD",
    title: "LedgerLens",
    description:
      "Real-time financial analytics dashboard with AI-powered forecasting, customisable chart widgets, CSV/PDF export, and multi-account consolidation. Built for indie founders and small finance teams.",
    features: [
      "Real-time P&L, cashflow, and burn rate dashboards with live data",
      "AI forecasting engine with scenario modelling and anomaly alerts",
      "Multi-account consolidation with CSV, PDF, and Notion export",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Recharts",
      "Prisma",
      "PostgreSQL",
      "OpenAI",
    ],
    color: "#059669",
    link: "#",
    github: "#",
    year: "2025",
    role: "Full-Stack Developer",
    status: "Beta",
    featured: false,
    images: {
      topLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Ledger+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Ledger+Mobile+2",
      right:
        "https://placehold.co/800x600/111111/ffffff?text=LedgerLens+Desktop",
      thumb: "https://placehold.co/600x400/001208/ffffff?text=LedgerLens",
    },
  },
];

const N = PROJECTS.length;
const SPRING = { type: "spring", stiffness: 60, damping: 20, mass: 1 } as const;
const CONTENT_SPRING = { type: "spring", stiffness: 80, damping: 24 } as const;
const ANIM_LOCK_MS = 650;

/* ─────────────────────────────────────────────
   NAV BUTTON
───────────────────────────────────────────── */
const NavButton = memo(function NavButton({
  onClick,
  disabled,
  direction,
  label,
}: {
  onClick: () => void;
  disabled: boolean;
  direction: "prev" | "next";
  label: string;
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      aria-label={label}
      className="
        group w-10 h-10 rounded-full
        border border-border
        bg-card/40 backdrop-blur-sm
        flex items-center justify-center
        transition-all duration-200
        disabled:opacity-30 disabled:cursor-not-allowed
        hover:border-foreground/30 hover:bg-card/70
        focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent
      "
    >
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={`text-muted-foreground group-hover:text-foreground transition-colors ${
          direction === "prev" ? "rotate-90" : "-rotate-90"
        }`}
      >
        <path d="M18 15l-6-6-6 6" />
      </svg>
    </button>
  );
});

/* ─────────────────────────────────────────────
   DESKTOP: IMAGE GROUP
───────────────────────────────────────────── */
const ImageGroup = memo(function ImageGroup({
  project,
  direction,
}: {
  project: Project;
  direction: number;
}) {
  const variants = {
    enter: (dir: number) => ({ y: dir === 1 ? "100%" : "-100%", scale: 0.96 }),
    center: { y: 0, scale: 1, transition: SPRING },
    exit: (dir: number) => ({
      y: dir === 1 ? "-100%" : "100%",
      scale: 0.96,
      transition: SPRING,
    }),
  };

  return (
    <motion.div
      key={project.id}
      custom={direction}
      variants={variants}
      initial="enter"
      animate="center"
      exit="exit"
      className="absolute inset-0 grid grid-cols-2 grid-rows-2 gap-3 p-1"
    >
      <div
        className="rounded-2xl overflow-hidden"
        style={{ background: project.color }}
      >
        <img
          src={project.images.topLeft}
          alt={`${project.title} — mobile view 1`}
          loading="lazy"
          className="w-full h-full object-cover opacity-90"
        />
      </div>
      <div
        className="rounded-2xl overflow-hidden row-start-2"
        style={{ background: project.color }}
      >
        <img
          src={project.images.bottomLeft}
          alt={`${project.title} — mobile view 2`}
          loading="lazy"
          className="w-full h-full object-cover opacity-90"
        />
      </div>
      <div
        className="rounded-2xl overflow-hidden row-span-2 col-start-2 row-start-1 relative group"
        style={{
          background: project.color + "22",
          border: `1px solid ${project.color}44`,
        }}
      >
        <img
          src={project.images.right}
          alt={`${project.title} — desktop view`}
          loading="lazy"
          className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-500"
        />
        <a
          href={project.link}
          aria-label={`Visit ${project.title}`}
          target="_blank"
          rel="noopener noreferrer"
          className="absolute bottom-4 right-4 w-20 h-20 rounded-full bg-foreground flex items-center justify-center hover:scale-105 transition-transform"
        >
          <svg
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            className="text-background"
          >
            <path d="M7 17L17 7M17 7H7M17 7v10" />
          </svg>
          <span className="sr-only">Visit {project.title}</span>
        </a>
        <p className="absolute bottom-4 right-4 text-[9px] tracking-[0.25em] uppercase text-background/60 w-20 h-20 flex items-center justify-center rounded-full pointer-events-none">
          Visit · Project
        </p>
      </div>
    </motion.div>
  );
});

/* ─────────────────────────────────────────────
   DESKTOP: CONTENT PANEL
───────────────────────────────────────────── */
const ContentPanel = memo(function ContentPanel({
  project,
  direction,
  onPrev,
  onNext,
  activeIndex,
}: {
  project: Project;
  direction: number;
  onPrev: () => void;
  onNext: () => void;
  activeIndex: number;
}) {
  const variants = {
    enter: (dir: number) => ({ y: dir === 1 ? 40 : -40, opacity: 0 }),
    center: { y: 0, opacity: 1, transition: CONTENT_SPRING },
    exit: (dir: number) => ({
      y: dir === 1 ? -40 : 40,
      opacity: 0,
      transition: { duration: 0.25, ease: "easeIn" as const },
    }),
  };

  return (
    <div className="flex flex-col h-full justify-center gap-8">
      <AnimatePresence custom={direction} mode="wait">
        <motion.div
          key={project.id}
          custom={direction}
          variants={variants}
          initial="enter"
          animate="center"
          exit="exit"
          className="flex flex-col gap-5"
        >
          <div className="flex items-center gap-3">
            <p className="section-label">{project.category}</p>
            <span
              className="text-[9px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full"
              style={{ background: project.color + "22", color: project.color }}
            >
              {project.status}
            </span>
          </div>

          <h2 className="font-display text-5xl lg:text-6xl xl:text-7xl leading-none">
            {project.title}
          </h2>

          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <span>{project.year}</span>
            <span className="w-1 h-1 rounded-full bg-border" />
            <span>{project.role}</span>
          </div>

          <p className="text-muted-foreground text-sm lg:text-base leading-relaxed max-w-sm">
            {project.description}
          </p>

          <ul className="flex flex-col gap-2.5">
            {project.features.map((f, i) => (
              <li
                key={i}
                className="flex items-start gap-3 text-sm text-foreground/80"
              >
                <span
                  className="mt-1 w-3.5 h-3.5 flex-shrink-0"
                  style={{ color: project.color }}
                >
                  <svg viewBox="0 0 14 14" fill="none" aria-hidden="true">
                    <path
                      d="M2 7h10M7 2l5 5-5 5"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </span>
                {f}
              </li>
            ))}
          </ul>

          <div className="flex flex-wrap gap-2">
            {project.stack.map((tech) => (
              <span key={tech} className="tag-pill">
                {tech}
              </span>
            ))}
          </div>

          <div className="flex items-center gap-3 pt-1">
            <a
              href={project.link}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`Live demo of ${project.title}`}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-semibold uppercase tracking-wider text-background transition-opacity hover:opacity-80"
              style={{ background: project.color }}
            >
              <svg
                width="11"
                height="11"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                aria-hidden="true"
              >
                <path d="M7 17L17 7M17 7H7M17 7v10" />
              </svg>
              Live Demo
            </a>
            <a
              href={project.github}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`GitHub repository of ${project.title}`}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-semibold uppercase tracking-wider border border-border bg-card/40 backdrop-blur-sm text-foreground/70 hover:text-foreground transition-colors"
            >
              <svg
                width="11"
                height="11"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
              >
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844a9.59 9.59 0 0 1 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.02 10.02 0 0 0 22 12.017C22 6.484 17.522 2 12 2z" />
              </svg>
              GitHub
            </a>
          </div>
        </motion.div>
      </AnimatePresence>

      {/* Desktop nav buttons */}
      <div className="flex items-center gap-3">
        <NavButton
          onClick={onPrev}
          disabled={activeIndex === 0}
          direction="prev"
          label="Previous project"
        />
        <NavButton
          onClick={onNext}
          disabled={activeIndex === N - 1}
          direction="next"
          label="Next project"
        />
        <span className="text-[11px] tracking-widest text-muted-foreground tabular-nums ml-1">
          {String(activeIndex + 1).padStart(2, "0")} /{" "}
          {String(N).padStart(2, "0")}
        </span>
      </div>
    </div>
  );
});

/* ─────────────────────────────────────────────
   DESKTOP: TIMELINE
───────────────────────────────────────────── */
const Timeline = memo(function Timeline({
  current,
  total,
  color,
}: {
  current: number;
  total: number;
  color: string;
}) {
  return (
    <div
      className="flex flex-col items-center gap-3 h-full justify-center py-8"
      aria-hidden="true"
    >
      <div className="relative w-px flex-1 bg-border rounded-full overflow-hidden">
        <motion.div
          className="absolute top-0 left-0 right-0 rounded-full"
          style={{ background: color }}
          animate={{ height: `${((current + 1) / total) * 100}%` }}
          transition={SPRING}
        />
      </div>
      <div className="flex flex-col gap-3">
        {Array.from({ length: total }).map((_, i) => (
          <motion.div
            key={i}
            className="w-1.5 h-1.5 rounded-full"
            animate={{
              backgroundColor: i <= current ? color : "hsl(var(--border))",
              scale: i === current ? 1.4 : 1,
            }}
            transition={{ duration: 0.35 }}
          />
        ))}
      </div>
    </div>
  );
});

/* ─────────────────────────────────────────────
   MOBILE: SINGLE PROJECT CARD
───────────────────────────────────────────── */
const MobileProjectCard = memo(function MobileProjectCard({
  project,
  direction,
  index,
}: {
  project: Project;
  direction: number;
  index: number;
}) {
  const variants = {
    enter: (dir: number) => ({ x: dir === 1 ? 60 : -60, opacity: 0 }),
    center: {
      x: 0,
      opacity: 1,
      transition: { duration: 0.38, ease: [0.25, 0.46, 0.45, 0.94] as const },
    },
    exit: (dir: number) => ({
      x: dir === 1 ? -60 : 60,
      opacity: 0,
      transition: { duration: 0.25, ease: "easeIn" as const },
    }),
  };

  return (
    <AnimatePresence custom={direction} mode="wait">
      <motion.article
        key={project.id}
        custom={direction}
        variants={variants}
        initial="enter"
        animate="center"
        exit="exit"
        className="flex flex-col overflow-hidden rounded-3xl border border-white/[0.07] bg-white/[0.03] backdrop-blur-md"
        style={{
          boxShadow: `0 0 0 1px ${project.color}22, 0 24px 48px rgba(0,0,0,0.5)`,
        }}
        aria-label={`Project ${index + 1} of ${N}: ${project.title}`}
      >
        {/* Accent top line */}
        <div
          className="h-[2px] w-full flex-shrink-0"
          style={{
            background: `linear-gradient(90deg, transparent, ${project.color}, transparent)`,
          }}
        />

        {/* Hero image */}
        <div
          className="relative w-full aspect-[16/9] overflow-hidden"
          style={{ background: project.color + "18" }}
        >
          <img
            src={project.images.right}
            alt={`${project.title} — hero screenshot`}
            loading="lazy"
            className="w-full h-full object-cover opacity-80"
          />
          <div
            className="absolute inset-0"
            style={{
              background: `linear-gradient(to bottom, transparent 40%, rgba(0,0,0,0.8))`,
            }}
          />
          {/* Status + year badge */}
          <div className="absolute top-3 left-3 flex gap-2">
            <span
              className="text-[9px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full backdrop-blur-sm"
              style={{ background: project.color + "cc", color: "#fff" }}
            >
              {project.status}
            </span>
            <span className="text-[9px] font-semibold uppercase tracking-wider px-2.5 py-1 rounded-full bg-black/50 backdrop-blur-sm text-white/70">
              {project.year}
            </span>
          </div>
          {/* Visit badge */}
          <a
            href={project.link}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={`Visit ${project.title}`}
            className="absolute bottom-3 right-3 w-14 h-14 rounded-full bg-foreground/90 backdrop-blur-sm flex items-center justify-center hover:scale-105 active:scale-95 transition-transform"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              className="text-background"
              aria-hidden="true"
            >
              <path d="M7 17L17 7M17 7H7M17 7v10" />
            </svg>
          </a>
        </div>

        {/* Content */}
        <div className="flex flex-col gap-4 p-5">
          <div>
            <p
              className="text-[10px] font-semibold uppercase tracking-[0.22em] mb-1.5"
              style={{ color: project.color }}
            >
              {project.category}
            </p>
            <h3 className="font-display text-3xl font-black leading-tight text-foreground">
              {project.title}
            </h3>
            <p className="text-xs text-muted-foreground/60 mt-0.5">
              {project.role}
            </p>
          </div>

          <p className="text-sm text-muted-foreground leading-relaxed">
            {project.description}
          </p>

          <ul className="flex flex-col gap-2">
            {project.features.map((f, i) => (
              <li
                key={i}
                className="flex items-start gap-2.5 text-xs text-foreground/75"
              >
                <span
                  className="mt-0.5 w-3 h-3 flex-shrink-0"
                  style={{ color: project.color }}
                  aria-hidden="true"
                >
                  <svg viewBox="0 0 14 14" fill="none">
                    <path
                      d="M2 7h10M7 2l5 5-5 5"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </span>
                {f}
              </li>
            ))}
          </ul>

          {/* Stack */}
          <div className="flex flex-wrap gap-1.5">
            {project.stack.map((tech) => (
              <span
                key={tech}
                className="text-[9px] font-medium uppercase tracking-wide px-2 py-0.5 rounded-full bg-white/[0.06] border border-white/[0.08] text-foreground/60"
              >
                {tech}
              </span>
            ))}
          </div>

          {/* CTA */}
          <div className="flex gap-2.5 pt-1">
            <a
              href={project.link}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`Live demo of ${project.title}`}
              className="flex-1 flex items-center justify-center gap-1.5 py-3 rounded-2xl text-xs font-semibold uppercase tracking-wider text-white transition-opacity active:opacity-70"
              style={{ background: project.color }}
            >
              <svg
                width="11"
                height="11"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                aria-hidden="true"
              >
                <path d="M7 17L17 7M17 7H7M17 7v10" />
              </svg>
              Live Demo
            </a>
            <a
              href={project.github}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`GitHub repo of ${project.title}`}
              className="flex items-center justify-center gap-1.5 px-4 py-3 rounded-2xl text-xs font-semibold uppercase tracking-wider bg-white/[0.06] border border-white/[0.08] text-foreground/70 active:opacity-70"
            >
              <svg
                width="11"
                height="11"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
              >
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0 1 12 6.844a9.59 9.59 0 0 1 2.504.337c1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.02 10.02 0 0 0 22 12.017C22 6.484 17.522 2 12 2z" />
              </svg>
              GitHub
            </a>
          </div>
        </div>
      </motion.article>
    </AnimatePresence>
  );
});

/* ─────────────────────────────────────────────
   MOBILE PAGINATION DOTS
───────────────────────────────────────────── */
const MobileDots = memo(function MobileDots({
  total,
  current,
  color,
}: {
  total: number;
  current: number;
  color: string;
}) {
  return (
    <div
      className="flex items-center justify-center gap-2"
      role="tablist"
      aria-label="Project navigation"
    >
      {Array.from({ length: total }).map((_, i) => (
        <motion.div
          key={i}
          role="tab"
          aria-selected={i === current}
          aria-label={`Project ${i + 1}`}
          className="rounded-full"
          animate={{
            width: i === current ? 20 : 6,
            backgroundColor: i === current ? color : "hsl(var(--border))",
          }}
          style={{ height: 6 }}
          transition={{ duration: 0.3 }}
        />
      ))}
    </div>
  );
});

/* ─────────────────────────────────────────────
   MOBILE SHOWCASE
───────────────────────────────────────────── */
function MobileShowcase() {
  const [activeIndex, setActiveIndex] = useState(0);
  const [direction, setDirection] = useState(1);
  const touchStartX = useRef(0);
  const touchStartY = useRef(0);

  const project = PROJECTS[activeIndex];

  const goTo = useCallback(
    (next: number) => {
      if (next < 0 || next >= N) return;
      setDirection(next > activeIndex ? 1 : -1);
      setActiveIndex(next);
    },
    [activeIndex],
  );

  const goPrev = useCallback(() => goTo(activeIndex - 1), [goTo, activeIndex]);
  const goNext = useCallback(() => goTo(activeIndex + 1), [goTo, activeIndex]);

  // Touch swipe
  const onTouchStart = useCallback((e: React.TouchEvent) => {
    touchStartX.current = e.touches[0].clientX;
    touchStartY.current = e.touches[0].clientY;
  }, []);

  const onTouchEnd = useCallback(
    (e: React.TouchEvent) => {
      const dx = touchStartX.current - e.changedTouches[0].clientX;
      const dy = Math.abs(touchStartY.current - e.changedTouches[0].clientY);
      if (Math.abs(dx) < 40 || dy > Math.abs(dx)) return;
      if (dx > 0) goNext();
      else goPrev();
    },
    [goNext, goPrev],
  );

  // Keyboard nav for mobile (when mobile layout shown)
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft") goPrev();
      if (e.key === "ArrowRight") goNext();
      if (e.key === "Home") goTo(0);
      if (e.key === "End") goTo(N - 1);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [goPrev, goNext, goTo]);

  return (
    <section className="section-padding" aria-label="Project showcase">
      {/* Heading */}
      <div className="mb-6">
        <p className="section-label mb-2">VENTURE SHOWCASE</p>
        <h2 className="font-display text-5xl leading-none">
          VENTURE <span className="font-accent">Showcase</span>
        </h2>
      </div>

      {/* Counter */}
      <div className="flex items-center justify-between mb-4">
        <span className="text-xs text-muted-foreground tabular-nums font-medium">
          <span className="text-foreground font-bold">
            {String(activeIndex + 1).padStart(2, "0")}
          </span>
          {" / "}
          {String(N).padStart(2, "0")}
        </span>
        <div className="flex gap-2">
          <NavButton
            onClick={goPrev}
            disabled={activeIndex === 0}
            direction="prev"
            label="Previous project"
          />
          <NavButton
            onClick={goNext}
            disabled={activeIndex === N - 1}
            direction="next"
            label="Next project"
          />
        </div>
      </div>

      {/* Swipeable card */}
      <div
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
        className="relative min-h-[640px]"
        aria-live="polite"
      >
        <MobileProjectCard
          project={project}
          direction={direction}
          index={activeIndex}
        />
      </div>

      {/* Pagination dots */}
      <div className="mt-5">
        <MobileDots total={N} current={activeIndex} color={project.color} />
      </div>

      {/* Swipe hint — shown only at start */}
      <AnimatePresence>
        {activeIndex === 0 && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1, transition: { delay: 1 } }}
            exit={{ opacity: 0 }}
            className="mt-3 text-center text-[10px] uppercase tracking-[0.2em] text-muted-foreground/50"
          >
            Swipe or use arrow keys to navigate
          </motion.p>
        )}
      </AnimatePresence>
    </section>
  );
}

/* ─────────────────────────────────────────────
   DESKTOP SHOWCASE
   
   Architecture — discrete pixel segments (Apple-style):
   ──────────────────────────────────────────────────────
   Wrapper height = N × 100vh
   Each project owns one 100vh segment.
   
   window.scroll listener computes which segment the user
   is in using raw pixel math — no scrollYProgress float.
   
   advanceTo() enforces ±1 step at a time and locks
   further advances for ANIM_LOCK_MS while a transition
   is in flight, preventing project skipping on fast scroll.
   
   Keyboard: ArrowDown/Up, Home/End also trigger advanceTo.
   
   Sticky inner is released naturally when wrapper scrolls
   past — no spacer div, no artificial whitespace.
───────────────────────────────────────────── */
function DesktopShowcase() {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const [direction, setDirection] = useState(1);
  const isAnimating = useRef(false);
  const committedIndex = useRef(0);

  const advanceTo = useCallback((target: number) => {
    const clamped = Math.max(0, Math.min(N - 1, target));
    if (clamped === committedIndex.current) return;
    if (isAnimating.current) return;

    // Only move one step at a time
    const step = clamped > committedIndex.current ? 1 : -1;
    const next = committedIndex.current + step;

    isAnimating.current = true;
    committedIndex.current = next;
    setDirection(step);
    setActiveIndex(next);

    setTimeout(() => {
      isAnimating.current = false;
    }, ANIM_LOCK_MS);
  }, []);

  // Scroll listener — pixel-based segment detection
  useEffect(() => {
    const onScroll = () => {
      const wrapper = wrapperRef.current;
      if (!wrapper) return;
      const wrapperTop = wrapper.getBoundingClientRect().top + window.scrollY;
      const scrolledIn = window.scrollY - wrapperTop;
      const vh = window.innerHeight;
      const rawTarget = Math.floor(scrolledIn / vh);
      advanceTo(rawTarget);
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [advanceTo]);

  // Keyboard navigation
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowDown" || e.key === "ArrowRight") {
        e.preventDefault();
        advanceTo(committedIndex.current + 1);
      }
      if (e.key === "ArrowUp" || e.key === "ArrowLeft") {
        e.preventDefault();
        advanceTo(committedIndex.current - 1);
      }
      if (e.key === "Home") {
        e.preventDefault();
        advanceTo(0);
      }
      if (e.key === "End") {
        e.preventDefault();
        advanceTo(N - 1);
      }
    };

    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [advanceTo]);

  const goPrev = useCallback(
    () => advanceTo(committedIndex.current - 1),
    [advanceTo],
  );
  const goNext = useCallback(
    () => advanceTo(committedIndex.current + 1),
    [advanceTo],
  );

  const project = PROJECTS[activeIndex];

  return (
    <>
      {/* Section heading — normal scroll above sticky zone */}
      <section className="section-padding pb-0">
        <p className="section-label">VENTURE SHOWCASE</p>
        <h2 className="font-display text-6xl md:text-8xl lg:text-[7rem] leading-none mb-16">
          VENTURE <span className="font-accent">Showcase</span>
        </h2>
      </section>

      {/*
       * OUTER WRAPPER — height = N × 100vh
       * Provides scroll budget. Sticky inner pins inside it.
       * Sticky releases automatically when wrapper exits viewport.
       * Zero spacer divs needed.
       */}
      <div
        ref={wrapperRef}
        style={{ height: `${N * 100}vh` }}
        className="relative"
        aria-label="Project showcase — scroll to explore"
      >
        <div
          className="sticky top-0 h-screen w-full overflow-hidden bg-background flex items-stretch"
          role="region"
          aria-live="polite"
          aria-atomic="true"
        >
          {/* Edge fade overlays */}
          <div
            className="pointer-events-none absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-background to-transparent z-20"
            aria-hidden="true"
          />
          <div
            className="pointer-events-none absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-background to-transparent z-20"
            aria-hidden="true"
          />

          <div className="flex w-full h-full px-5 md:px-16 lg:px-24 py-10 gap-6 lg:gap-10">
            {/* LEFT: content + nav */}
            <div className="flex-1 flex items-center min-w-0">
              <div className="w-full max-w-sm">
                <ContentPanel
                  project={project}
                  direction={direction}
                  onPrev={goPrev}
                  onNext={goNext}
                  activeIndex={activeIndex}
                />
              </div>
            </div>

            {/* CENTER: timeline */}
            <div className="hidden md:flex w-8 flex-shrink-0">
              <Timeline current={activeIndex} total={N} color={project.color} />
            </div>

            {/* RIGHT: images */}
            <div className="flex-1 relative min-w-0 flex items-center">
              <div className="relative w-full h-[85vh] max-h-[700px]">
                <AnimatePresence custom={direction}>
                  <ImageGroup
                    key={project.id}
                    project={project}
                    direction={direction}
                  />
                </AnimatePresence>
              </div>
            </div>
          </div>

          {/* Scroll hint */}
          <AnimatePresence>
            {activeIndex === 0 && (
              <motion.div
                className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 pointer-events-none z-30"
                initial={{ opacity: 0, y: 10 }}
                animate={{
                  opacity: 1,
                  y: 0,
                  transition: { delay: 1.2, duration: 0.6 },
                }}
                exit={{ opacity: 0, transition: { duration: 0.4 } }}
                aria-hidden="true"
              >
                <p className="text-[10px] tracking-[0.3em] uppercase text-muted-foreground">
                  Scroll to explore
                </p>
                <motion.div
                  className="w-px h-8 bg-muted-foreground/40 origin-top"
                  animate={{ scaleY: [0.3, 1, 0.3] }}
                  transition={{
                    duration: 1.6,
                    repeat: Infinity,
                    ease: "easeInOut",
                  }}
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
      {/* Next section follows immediately — no spacer */}
    </>
  );
}

/* ─────────────────────────────────────────────
   MAIN EXPORT
───────────────────────────────────────────── */
export default function ProjectShowcase() {
  return (
    <>
      {/* Mobile: < lg */}
      <div className="block lg:hidden">
        <MobileShowcase />
      </div>
      {/* Desktop: ≥ lg */}
      <div className="hidden lg:block">
        <DesktopShowcase />
      </div>
    </>
  );
}
