import { useRef, useState, useEffect } from "react";
import {
  motion,
  AnimatePresence,
  useScroll,
  useTransform,
} from "framer-motion";

/* ─────────────────────────────────────────────
   DATA  –  swap in your real project data
───────────────────────────────────────────── */
const PROJECTS = [
  {
    id: 1,
    category: "PRODUCTIVITY · SAAS",
    title: "Rune",
    description:
      "Rune is your all-in-one productivity toolkit featuring 145+ powerful tools for learning, creating, and working smarter. From text & writing tools, PDF management, image editing, video processing, to developer utilities, calculators, and AI-powered assistants.",
    features: [
      "145+ free tools including text editors, PDF converters, and image processors",
      "AI-powered tools for writing, summarising, and content creation",
      "Developer utilities with JSON formatter, regex tester, and code tools",
    ],
    stack: ["React", "TypeScript", "Next.js", "Tailwind CSS", "RuneAI"],
    color: "#c0392b",
    images: {
      topLeft: "https://placehold.co/480x320/1a1a1a/ffffff?text=Rune+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Rune+Mobile+2",
      right: "https://placehold.co/800x600/111111/ffffff?text=Rune+Desktop",
    },
  },
  {
    id: 2,
    category: "EDUCATION · AI",
    title: "RuneLearn",
    description:
      "RuneLearn is an ultimate AI-powered study companion that dynamically generates quizzes, intelligent flashcards, personalised roadmaps, and instantly resolves doubts with its deep-context advanced doubt solver. Designed to turbocharge long-term memory.",
    features: [
      "Interactive Quizzes and Flashcards dynamically generated by AI",
      "Personalised Learning Roadmaps tailored to your study goals",
      "Advanced Doubt Solver providing in-depth explanations instantly",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "RuneAI",
      "Vercel",
    ],
    color: "#b45309",
    images: {
      topLeft: "https://placehold.co/480x320/1a1a1a/ffffff?text=Learn+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Learn+Mobile+2",
      right: "https://placehold.co/800x600/111111/ffffff?text=Learn+Desktop",
    },
  },
  {
    id: 3,
    category: "PORTFOLIO · TEMPLATE",
    title: "ParthSharma.me",
    description:
      "A premium, high-performance portfolio crafted for the modern web. Featuring fluid GSAP animations, physics-based interactions, and a polished aesthetic. Built with a robust stack including Next.js, Prisma, and Zustand, it sets a new standard for creative developers.",
    features: [
      "Premium, high-performance design with fluid GSAP animations",
      "Physics-based interactions and advanced state management",
      "Robust full-stack architecture with Prisma and Node.js",
    ],
    stack: [
      "React",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Tailwind CSS",
      "GSAP",
      "Prisma",
      "Zustand",
      "Motion",
      "Vercel",
    ],
    color: "#7c3aed",
    images: {
      topLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Portfolio+Mobile+1",
      bottomLeft:
        "https://placehold.co/480x320/1a1a1a/ffffff?text=Portfolio+Mobile+2",
      right:
        "https://placehold.co/800x600/111111/ffffff?text=Portfolio+Desktop",
    },
  },
];

/* ─────────────────────────────────────────────
   SPRING CONFIG
───────────────────────────────────────────── */
const SPRING = { type: "spring", stiffness: 60, damping: 20, mass: 1 };

/* ─────────────────────────────────────────────
   IMAGE CARD GROUP  –  three cards per project
───────────────────────────────────────────── */
function ImageGroup({ project, direction }) {
  const variants = {
    enter: (dir) => ({
      y: dir === 1 ? "100%" : "-100%",
      scale: 0.96,
    }),
    center: {
      y: 0,
      scale: 1,
      transition: SPRING,
    },
    exit: (dir) => ({
      y: dir === 1 ? "-100%" : "100%",
      scale: 0.96,
      transition: SPRING,
    }),
  };

  return (
    <motion.div
      key={project.id}
      custom={direction}
      variants={variants}
      initial="enter"
      animate="center"
      exit="exit"
      className="absolute inset-0 grid grid-cols-2 grid-rows-2 gap-3 p-1"
    >
      {/* top-left */}
      <div
        className="rounded-2xl overflow-hidden"
        style={{ background: project.color }}
      >
        <img
          src={project.images.topLeft}
          alt={project.title + " mobile view 1"}
          className="w-full h-full object-cover opacity-90"
        />
      </div>

      {/* bottom-left */}
      <div
        className="rounded-2xl overflow-hidden row-start-2"
        style={{ background: project.color }}
      >
        <img
          src={project.images.bottomLeft}
          alt={project.title + " mobile view 2"}
          className="w-full h-full object-cover opacity-90"
        />
      </div>

      {/* large right — spans both rows */}
      <div
        className="rounded-2xl overflow-hidden row-span-2 col-start-2 row-start-1 relative group cursor-pointer"
        style={{
          background: project.color + "22",
          border: `1px solid ${project.color}44`,
        }}
      >
        <img
          src={project.images.right}
          alt={project.title + " desktop view"}
          className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-500"
        />
        {/* visit project badge */}
        <div className="absolute bottom-4 right-4 w-20 h-20 rounded-full bg-foreground flex items-center justify-center">
          <svg
            width="18"
            height="18"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            className="text-background"
          >
            <path d="M7 17L17 7M17 7H7M17 7v10" />
          </svg>
        </div>
        <div
          className="absolute bottom-4 right-4 w-20 h-20 rounded-full"
          style={{
            background: "transparent",
            border: "1px solid rgba(255,255,255,0.2)",
          }}
        />
        <p className="absolute bottom-4 right-4 text-[9px] tracking-[0.25em] uppercase text-background/60 w-20 h-20 flex items-center justify-center rounded-full">
          Visit ·&nbsp;Project
        </p>
      </div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────
   LEFT CONTENT PANEL
───────────────────────────────────────────── */
function ContentPanel({ project, direction }) {
  const variants = {
    enter: (dir) => ({ y: dir === 1 ? 40 : -40, opacity: 0 }),
    center: {
      y: 0,
      opacity: 1,
      transition: { ...SPRING, stiffness: 80, damping: 24 },
    },
    exit: (dir) => ({
      y: dir === 1 ? -40 : 40,
      opacity: 0,
      transition: { duration: 0.3, ease: "easeIn" },
    }),
  };

  return (
    <AnimatePresence custom={direction} mode="wait">
      <motion.div
        key={project.id}
        custom={direction}
        variants={variants}
        initial="enter"
        animate="center"
        exit="exit"
        className="flex flex-col gap-6"
      >
        {/* category */}
        <p className="section-label">{project.category}</p>

        {/* title */}
        <h2 className="font-display text-5xl lg:text-6xl xl:text-7xl leading-none">
          {project.title}
        </h2>

        {/* description */}
        <p className="text-muted-foreground text-sm lg:text-base leading-relaxed max-w-sm">
          {project.description}
        </p>

        {/* features */}
        <ul className="flex flex-col gap-3">
          {project.features.map((f, i) => (
            <li
              key={i}
              className="flex items-start gap-3 text-sm text-foreground/80"
            >
              <span
                className="mt-1 w-3.5 h-3.5 flex-shrink-0"
                style={{ color: project.color }}
              >
                <svg viewBox="0 0 14 14" fill="none">
                  <path
                    d="M2 7h10M7 2l5 5-5 5"
                    stroke="currentColor"
                    strokeWidth="1.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </span>
              {f}
            </li>
          ))}
        </ul>

        {/* tech stack */}
        <div className="flex flex-wrap gap-2 pt-2">
          {project.stack.map((tech) => (
            <span key={tech} className="tag-pill">
              {tech}
            </span>
          ))}
        </div>
      </motion.div>
    </AnimatePresence>
  );
}

/* ─────────────────────────────────────────────
   TIMELINE
───────────────────────────────────────────── */
function Timeline({ current, total, color }) {
  return (
    <div className="flex flex-col items-center gap-2 h-full justify-center py-8">
      {/* progress track */}
      <div className="relative w-px flex-1 bg-border rounded-full overflow-hidden">
        <motion.div
          className="absolute top-0 left-0 right-0 rounded-full"
          style={{ background: color }}
          animate={{ height: `${((current + 1) / total) * 100}%` }}
          transition={SPRING}
        />
      </div>

      {/* dots */}
      <div className="flex flex-col gap-4">
        {Array.from({ length: total }).map((_, i) => (
          <motion.div
            key={i}
            className="w-1.5 h-1.5 rounded-full"
            animate={{
              background: i <= current ? color : "hsl(var(--border))",
              scale: i === current ? 1.4 : 1,
            }}
            transition={{ duration: 0.4 }}
          />
        ))}
      </div>

      {/* counter */}
      <p className="text-[10px] tracking-widest text-muted-foreground mt-2 tabular-nums">
        {String(current + 1).padStart(2, "0")}/{String(total).padStart(2, "0")}
      </p>
    </div>
  );
}

/* ─────────────────────────────────────────────
   MAIN SECTION
───────────────────────────────────────────── */
export default function ProjectShowcase() {
  const sectionRef = useRef(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const [direction, setDirection] = useState(1);
  const [isPinned, setIsPinned] = useState(false);
  const lastScrollY = useRef(0);
  const accumulatedDelta = useRef(0);
  const SCROLL_THRESHOLD = 120; // px of scroll needed to trigger next project

  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsPinned(entry.isIntersecting && entry.intersectionRatio >= 0.8);
      },
      { threshold: 0.8 },
    );
    observer.observe(section);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const handleWheel = (e) => {
      if (!isPinned) return;

      const goingDown = e.deltaY > 0;
      const goingUp = e.deltaY < 0;

      // Allow normal scroll at edges
      if (goingDown && activeIndex === PROJECTS.length - 1) return;
      if (goingUp && activeIndex === 0) return;

      e.preventDefault();
      accumulatedDelta.current += e.deltaY;

      if (accumulatedDelta.current >= SCROLL_THRESHOLD) {
        accumulatedDelta.current = 0;
        setDirection(1);
        setActiveIndex((i) => Math.min(i + 1, PROJECTS.length - 1));
      } else if (accumulatedDelta.current <= -SCROLL_THRESHOLD) {
        accumulatedDelta.current = 0;
        setDirection(-1);
        setActiveIndex((i) => Math.max(i - 1, 0));
      }
    };

    window.addEventListener("wheel", handleWheel, { passive: false });
    return () => window.removeEventListener("wheel", handleWheel);
  }, [isPinned, activeIndex]);

  // touch support
  useEffect(() => {
    let touchStartY = 0;

    const onTouchStart = (e) => {
      touchStartY = e.touches[0].clientY;
    };

    const onTouchEnd = (e) => {
      if (!isPinned) return;
      const dy = touchStartY - e.changedTouches[0].clientY;
      if (Math.abs(dy) < 40) return;

      if (dy > 0 && activeIndex < PROJECTS.length - 1) {
        setDirection(1);
        setActiveIndex((i) => i + 1);
      } else if (dy < 0 && activeIndex > 0) {
        setDirection(-1);
        setActiveIndex((i) => i - 1);
      }
    };

    window.addEventListener("touchstart", onTouchStart, { passive: true });
    window.addEventListener("touchend", onTouchEnd, { passive: true });
    return () => {
      window.removeEventListener("touchstart", onTouchStart);
      window.removeEventListener("touchend", onTouchEnd);
    };
  }, [isPinned, activeIndex]);

  const project = PROJECTS[activeIndex];

  return (
    <>
      {/* section label above */}
      <section className="section-padding pb-0">
        <p className="section-label">VENTURE SHOWCASE</p>
        <h2 className="font-display text-6xl md:text-8xl lg:text-[7rem] leading-none mb-16">
          VENTURE <span className="font-accent">Showcase</span>
        </h2>
      </section>

      {/* ── PINNED STAGE ── */}
      <div
        ref={sectionRef}
        className="sticky top-0 h-screen w-full overflow-hidden bg-background flex items-stretch"
        style={{ zIndex: 10 }}
      >
        {/* subtle gradient overlay top + bottom */}
        <div className="pointer-events-none absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-background to-transparent z-20" />
        <div className="pointer-events-none absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-background to-transparent z-20" />

        <div className="flex w-full h-full px-5 md:px-16 lg:px-24 py-10 gap-6 lg:gap-10">
          {/* ── LEFT: content ── */}
          <div className="flex-1 flex items-center min-w-0">
            <div className="w-full max-w-sm">
              <ContentPanel project={project} direction={direction} />
            </div>
          </div>

          {/* ── CENTER: timeline ── */}
          <div className="hidden md:flex w-8 flex-shrink-0">
            <Timeline
              current={activeIndex}
              total={PROJECTS.length}
              color={project.color}
            />
          </div>

          {/* ── RIGHT: image conveyor belt ── */}
          <div className="flex-1 relative min-w-0 flex items-center">
            <div className="relative w-full h-[85vh] max-h-[700px]">
              <AnimatePresence custom={direction}>
                <ImageGroup
                  key={project.id}
                  project={project}
                  direction={direction}
                />
              </AnimatePresence>
            </div>
          </div>
        </div>

        {/* scroll hint — fades after first interaction */}
        <AnimatePresence>
          {activeIndex === 0 && (
            <motion.div
              className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 pointer-events-none z-30"
              initial={{ opacity: 0, y: 10 }}
              animate={{
                opacity: 1,
                y: 0,
                transition: { delay: 1.2, duration: 0.6 },
              }}
              exit={{ opacity: 0, transition: { duration: 0.4 } }}
            >
              <p className="text-[10px] tracking-[0.3em] uppercase text-muted-foreground">
                Scroll to explore
              </p>
              <motion.div
                className="w-px h-8 bg-muted-foreground/40 origin-top"
                animate={{ scaleY: [0.3, 1, 0.3] }}
                transition={{
                  duration: 1.6,
                  repeat: Infinity,
                  ease: "easeInOut",
                }}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* spacer so the pinned section has room to scroll through */}
      <div
        style={{ height: `${(PROJECTS.length - 1) * 100}vh` }}
        aria-hidden="true"
      />
    </>
  );
}
